apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-lab

spec:
  replicas: 2
  selector:
   matchLabels:
     app: fastapi-lab
  template:
    metadata:
     labels:
       app: faastapi-lab
    spec:
     containers:
     -name: fastapi-lab
      image: fastapi-fixed:1.0
      imagePullPolicy: Never
      ports:
      - containerPort: 8000



